<!DOCTYPE html>
<html>
<head>
  <title>Export PDF</title>
  <style>
    body {
      font-family: Arial, sans-serif;
    }
  </style>
</head>
<body>
<p>This is a sample PDF generated by Laravel and DomPDF.</p>
</body>
</html>
